/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Account;
import jooq.tables.Customer;
import jooq.tables.Transfer;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.account</code>.
     */
    public static final Account ACCOUNT = jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.customer</code>.
     */
    public static final Customer CUSTOMER = jooq.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.transfer</code>.
     */
    public static final Transfer TRANSFER = jooq.tables.Transfer.TRANSFER;
}
